name: new site
source:      _source
destination: _deploy
markdown : kramdown
gems:
  - jekyll-sitemap
   kramdown:
   input: GFM
   hard_wrap: false
   gems:
   - jekyll-coffeescript
   - jekyll-paginate
  
